name: Build Rust Project (Matrix)

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    name: Build on ${{ matrix.os }} (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: linux-amd64-binary
            binary_path: target/release/mmr

          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: macos-arm64-binary
            binary_path: target/aarch64-apple-darwin/release/mmr

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            cargo build --release
          else
            cargo build --release --target=${{ matrix.target }}
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.binary_path }}

